### ISSUE TITLE
Randomness control

### ISSUE THREAD

**Issue by zhengli09** [haotianteng/FICT#1]
Hi Haotian,

Very interesting method! I am wondering whether FICT has a way to control its model randomness (ex. seed)? It seems the clustering assignments are different if I run the model on the same data for different times. It would be very helpful if I can reproduce the same results! Let me know if I miss anything. Thank you!

**Comment by haotianteng** [comment]
Currently, there is no such random control implemented, one way to do it is to load the same embedding, and set the random seed before every run. Check the run.py script.
